### ISSUE TITLE
Request for some related files in decoupling_emt_stroma

### ISSUE THREAD

**Issue by fengwanwan** [m20ty/decoupling_emt_stroma#1]
Dear Michael Tyler:
         Thanks for your wonderful study for decoupling the EMT. Unfortunately, When I'm reproducing the code, there are not the related files,such as "cell_type_markers.csv","emt_markers.csv","CCLE_cancer_type_Av.csv". I am writing to ask whether you could upload or send those files. Thank you.

**Comment by m20ty** [comment]
Dear Wanwan
Thank you for your interest in our study.  I sent you the files by email.
Best wishes
Mike

**Comment by kirkupc** [comment]
Hello, 

Thanks very much for the excellent research! Would it be possible to share copies of the above-mentioned files with me as well?

Best,
Chris

**Comment by m20ty** [comment]
Hi Chris
I've attached the files that Wanwan asked for, plus another one containing tumour purity values, which may be necessary to run the code.
Thanks and all the best
Mike

[CCLE_cancer_type_Av.csv](https://github.com/m20ty/decoupling_emt_stroma/files/8630672/CCLE_cancer_type_Av.csv)
[cell_type_markers.csv](https://github.com/m20ty/decoupling_emt_stroma/files/8630673/cell_type_markers.csv)
[emt_markers.csv](https://github.com/m20ty/decoupling_emt_stroma/files/8630674/emt_markers.csv)
[tcga_annotations.csv](https://github.com/m20ty/decoupling_emt_stroma/files/8630675/tcga_annotations.csv)

**Comment by kirkupc** [comment]
Hi Mike, 

Thanks very much for sharing the above files - I appreciate your help!

Best,
Chris
